# Generated by Django 3.2 on 2021-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAlert',
            fields=[
                ('alert_id', models.AutoField(db_column='Alert_Id', primary_key=True, serialize=False)),
                ('band_mac', models.CharField(db_column='Band_Mac', max_length=50)),
                ('alert_date', models.DateField(blank=True, db_column='Alert_Date', null=True)),
                ('alert_time', models.TimeField(blank=True, db_column='Alert_Time', null=True)),
                ('alert_code', models.IntegerField(db_column='Alert_Code')),
            ],
            options={
                'db_table': 'tbl_alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDevice',
            fields=[
                ('device_id', models.AutoField(db_column='Device_Id', primary_key=True, serialize=False)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_Updated_Date', null=True)),
                ('last_updated_time', models.TimeField(blank=True, db_column='Last_Updated_Time', null=True)),
                ('band_mac', models.CharField(db_column='Band_Mac', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblIncoming',
            fields=[
                ('incoming_id', models.AutoField(db_column='Incoming_Id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('gateway_mac', models.CharField(db_column='Gateway_Mac', max_length=50)),
                ('band_mac', models.CharField(db_column='Band_Mac', max_length=50)),
                ('blename', models.CharField(blank=True, db_column='BleName', max_length=50, null=True)),
                ('rssi', models.IntegerField(db_column='Rssi')),
                ('temperature', models.FloatField(db_column='Temperature')),
                ('heartrate', models.CharField(blank=True, db_column='HeartRate', max_length=45, null=True)),
                ('batterylevel', models.IntegerField(blank=True, db_column='BatteryLevel', null=True)),
            ],
            options={
                'db_table': 'tbl_incoming',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSubscription',
            fields=[
                ('subscription_id', models.AutoField(db_column='Subscription_Id', primary_key=True, serialize=False)),
                ('band_mac', models.CharField(db_column='Band_Mac', max_length=45)),
            ],
            options={
                'db_table': 'tbl_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('user_id', models.AutoField(db_column='User_Id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_Name', max_length=50)),
                ('user_login', models.CharField(db_column='User_LogIn', max_length=50)),
                ('user_pwd', models.CharField(db_column='User_Pwd', max_length=50)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
    ]
