# Generated by Django 3.2 on 2021-05-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblalert',
            options={'managed': False, 'verbose_name': 'TBL_Alert', 'verbose_name_plural': 'TBL_Alert'},
        ),
        migrations.AlterModelOptions(
            name='tbldevice',
            options={'managed': False, 'verbose_name': 'TBL_Device', 'verbose_name_plural': 'TBL_Device'},
        ),
        migrations.AlterModelOptions(
            name='tblincoming',
            options={'managed': False, 'verbose_name': 'TBL_Incoming', 'verbose_name_plural': 'TBL_Incoming'},
        ),
        migrations.AlterModelOptions(
            name='tblsubscription',
            options={'managed': False, 'verbose_name': 'TBL_Subscription', 'verbose_name_plural': 'TBL_Subscription'},
        ),
        migrations.AlterModelOptions(
            name='tbluser',
            options={'managed': False, 'verbose_name': 'TBL_User', 'verbose_name_plural': 'TBL_User'},
        ),
    ]
