# Generated by Django 3.2 on 2021-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAcknowledgement',
            fields=[
                ('ack_id', models.CharField(db_column='Ack_ID', max_length=50, primary_key=True, serialize=False)),
                ('ack_date', models.DateField(db_column='Ack_Date')),
                ('ack_time', models.TimeField(db_column='Ack_Time')),
                ('alert_id', models.CharField(db_column='Alert_ID', max_length=50)),
            ],
            options={
                'db_table': 'tbl_acknowledgement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_Name', max_length=50)),
                ('user_email', models.CharField(db_column='User_Email', max_length=50)),
                ('user_login', models.CharField(db_column='User_LogIn', max_length=50)),
                ('user_pwd', models.CharField(db_column='User_Pwd', max_length=50)),
                ('org_id', models.CharField(db_column='Org_ID', max_length=50)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
    ]
