# Generated by Django 3.2 on 2021-06-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_tblacknowledgement_tbluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblAcknowledgement',
        ),
        migrations.DeleteModel(
            name='TblUser',
        ),
    ]
