# Generated by Django 3.2 on 2021-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20210609_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAcknowledgement',
            fields=[
                ('ack_id', models.CharField(db_column='Ack_ID', max_length=50, primary_key=True, serialize=False)),
                ('ack_date', models.DateField(db_column='Ack_Date')),
                ('ack_time', models.TimeField(db_column='Ack_Time')),
                ('alert_id', models.CharField(db_column='Alert_ID', max_length=50)),
            ],
            options={
                'db_table': 'tbl_acknowledgement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAlert',
            fields=[
                ('alert_id', models.CharField(db_column='Alert_ID', max_length=50, primary_key=True, serialize=False)),
                ('alert_reading', models.CharField(db_column='Alert_Reading', max_length=10)),
                ('alert_date', models.DateField(blank=True, db_column='Alert_Date', null=True)),
                ('alert_time', models.TimeField(blank=True, db_column='Alert_Time', null=True)),
            ],
            options={
                'db_table': 'tbl_alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAlertCode',
            fields=[
                ('alert_code', models.CharField(db_column='Alert_Code', max_length=10, primary_key=True, serialize=False)),
                ('alert_description', models.CharField(db_column='Alert_Description', max_length=50)),
            ],
            options={
                'db_table': 'tbl_alert_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCrestPatient',
            fields=[
                ('patient_id', models.CharField(db_column='Patient_ID', max_length=50, primary_key=True, serialize=False)),
                ('patient_tag', models.CharField(db_column='Patient_Tag', max_length=50)),
                ('band_tag', models.CharField(db_column='Band_Tag', max_length=50)),
                ('created_date', models.DateField(db_column='Created_Date')),
                ('created_time', models.TimeField(db_column='Created_Time')),
            ],
            options={
                'db_table': 'tbl_crest_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDailySurvey',
            fields=[
                ('daily_survey_id', models.CharField(db_column='Daily_Survey_ID', max_length=50, primary_key=True, serialize=False)),
                ('daily_survey_q1', models.IntegerField(blank=True, db_column='Daily_Survey_Q1', null=True)),
                ('daily_survey_q2_y1', models.IntegerField(blank=True, db_column='Daily_Survey_Q2_Y1', null=True)),
                ('daily_survey_q2_y2', models.IntegerField(blank=True, db_column='Daily_Survey_Q2_Y2', null=True)),
                ('daily_survey_q2_y3', models.IntegerField(blank=True, db_column='Daily_Survey_Q2_Y3', null=True)),
                ('daily_survey_q2_y4', models.IntegerField(blank=True, db_column='Daily_Survey_Q2_Y4', null=True)),
                ('daily_survey_q2_y5', models.IntegerField(blank=True, db_column='Daily_Survey_Q2_Y5', null=True)),
                ('daily_survey_q3', models.IntegerField(blank=True, db_column='Daily_Survey_Q3', null=True)),
                ('daily_survey_date', models.DateField(blank=True, db_column='Daily_Survey_Date', null=True)),
                ('daily_survey_time', models.TimeField(blank=True, db_column='Daily_Survey_Time', null=True)),
                ('daily_survey_session', models.CharField(blank=True, db_column='Daily_Survey_Session', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_daily_survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDevice',
            fields=[
                ('device_id', models.CharField(db_column='Device_ID', max_length=50, primary_key=True, serialize=False)),
                ('device_type', models.CharField(db_column='Device_Type', max_length=50)),
                ('device_serial_no', models.CharField(db_column='Device_Serial_No', max_length=50)),
                ('device_mac', models.CharField(db_column='Device_Mac', max_length=50, unique=True)),
                ('device_bat_level', models.IntegerField(blank=True, db_column='Device_Bat_Level', null=True)),
                ('device_last_updated_date', models.DateField(blank=True, db_column='Device_Last_Updated_Date', null=True)),
                ('device_last_updated_time', models.TimeField(blank=True, db_column='Device_Last_Updated_Time', null=True)),
                ('device_temp', models.FloatField(blank=True, db_column='Device_Temp', null=True)),
                ('device_hr', models.CharField(blank=True, db_column='Device_HR', max_length=50, null=True)),
                ('device_o2', models.IntegerField(blank=True, db_column='Device_O2', null=True)),
                ('incoming_id', models.IntegerField(blank=True, db_column='Incoming_Id', null=True)),
                ('device_rssi', models.CharField(blank=True, db_column='Device_RSSI', max_length=50, null=True)),
                ('gateway_mac', models.CharField(blank=True, db_column='Gateway_Mac', max_length=45, null=True)),
                ('incorrect_data_flag', models.IntegerField(db_column='Incorrect_Data_Flag')),
                ('device_status', models.CharField(blank=True, db_column='Device_Status', max_length=10, null=True)),
                ('device_tag', models.CharField(blank=True, db_column='Device_Tag', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDeviceRawLength',
            fields=[
                ('device_type', models.CharField(db_column='Device_Type', max_length=50, primary_key=True, serialize=False)),
                ('raw_data_length', models.IntegerField(db_column='Raw_Data_Length')),
            ],
            options={
                'db_table': 'tbl_device_raw_length',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGateway',
            fields=[
                ('gateway_id', models.CharField(db_column='Gateway_ID', max_length=50, primary_key=True, serialize=False)),
                ('gateway_location', models.CharField(db_column='Gateway_Location', max_length=50)),
                ('gateway_address', models.CharField(db_column='Gateway_Address', max_length=50)),
                ('gateway_mac', models.CharField(db_column='Gateway_Mac', max_length=50)),
                ('gateway_serial_no', models.CharField(db_column='Gateway_Serial_No', max_length=50)),
                ('gateway_topic', models.CharField(db_column='Gateway_Topic', max_length=50)),
                ('gateway_latitude', models.CharField(db_column='Gateway_Latitude', max_length=50)),
                ('gateway_longitude', models.CharField(db_column='Gateway_Longitude', max_length=50)),
                ('gateway_type', models.CharField(db_column='Gateway_Type', max_length=50)),
            ],
            options={
                'db_table': 'tbl_gateway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblIncoming',
            fields=[
                ('incoming_id', models.CharField(db_column='Incoming_ID', max_length=50, primary_key=True, serialize=False)),
                ('incoming_device_mac', models.CharField(db_column='Incoming_Device_Mac', max_length=50)),
                ('incoming_gateway_mac', models.CharField(db_column='Incoming_Gateway_Mac', max_length=50)),
                ('incoming_temp', models.FloatField(db_column='Incoming_Temp')),
                ('incoming_o2', models.IntegerField(db_column='Incoming_O2')),
                ('incoming_hr', models.CharField(blank=True, db_column='Incoming_HR', max_length=45, null=True)),
                ('incoming_date', models.DateField(db_column='Incoming_Date')),
                ('incoming_time', models.TimeField(db_column='Incoming_Time')),
                ('device_status', models.CharField(blank=True, db_column='Device_Status', max_length=50, null=True)),
                ('incorrect_data_flag', models.IntegerField(blank=True, db_column='Incorrect_Data_Flag', null=True)),
                ('device_bat_level', models.IntegerField(blank=True, db_column='Device_Bat_Level', null=True)),
                ('device_rssi', models.CharField(blank=True, db_column='Device_RSSI', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_incoming',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMessage',
            fields=[
                ('message_id', models.CharField(db_column='Message_ID', max_length=50, primary_key=True, serialize=False)),
                ('message_description', models.CharField(db_column='Message_Description', max_length=100)),
                ('message_date', models.DateField(db_column='Message_Date')),
                ('message_time', models.TimeField(db_column='Message_Time')),
                ('message_type', models.CharField(db_column='Message_Type', max_length=50)),
                ('wearer_id', models.CharField(blank=True, db_column='Wearer_ID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrganization',
            fields=[
                ('org_id', models.CharField(db_column='Org_ID', max_length=50, primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_column='Org_Name', max_length=50)),
                ('org_rep', models.CharField(db_column='Org_Rep', max_length=50)),
                ('org_rep_email', models.CharField(db_column='Org_Rep_Email', max_length=50)),
                ('org_address', models.CharField(db_column='Org_Address', max_length=100)),
            ],
            options={
                'db_table': 'tbl_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSubscription',
            fields=[
                ('subscription_id', models.CharField(db_column='Subscription_ID', max_length=50, primary_key=True, serialize=False)),
                ('subscription_created_date', models.DateField(db_column='Subscription_Created_Date')),
                ('subscription_created_time', models.TimeField(db_column='Subscription_Created_Time')),
            ],
            options={
                'db_table': 'tbl_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_Name', max_length=50)),
                ('user_email', models.CharField(db_column='User_Email', max_length=50)),
                ('user_login', models.CharField(db_column='User_LogIn', max_length=50)),
                ('user_pwd', models.CharField(db_column='User_Pwd', max_length=50)),
                ('org_id', models.CharField(db_column='Org_ID', max_length=50)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWearer',
            fields=[
                ('wearer_id', models.CharField(db_column='Wearer_ID', max_length=50, primary_key=True, serialize=False)),
                ('wearer_nick', models.CharField(db_column='Wearer_Nick', max_length=50, unique=True)),
                ('wearer_pwd', models.CharField(db_column='Wearer_Pwd', max_length=50)),
            ],
            options={
                'db_table': 'tbl_wearer',
                'managed': False,
            },
        ),
    ]
