# Generated by Django 3.2 on 2021-06-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_tblacknowledgement_tblalert_tblalertcode_tblcrestpatient_tbldailysurvey_tbldevice_tbldevicerawlength'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
